version: "3"

services:
  app:
    container_name: schedula_location
    image: schedula/location
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    volumes:
      - ".:/code/"
    ports:
      - "3001:3000"
    environment:
      - ENVIRONMENT=DEVELOPMENT
      - NODE_ENV=DEVELOPMENT
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_DB=schedula_location
      - DATABASE_PORT=5432

  postgres:
    image: postgres:alpine
    container_name: schedula_location_db
    ports:
      - "5104:5432"
    volumes:
      - ./.ignore/postgres/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=schedula_location

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "schedula@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "schedula123!"
    ports:
      - "16544:80"
    depends_on:
      - postgres